### PR TITLE
extend internal transaction timeout

### PR DESCRIPTION
**Pull request by crypto-facs**
Extend `debug_traceTransaction` default timeout

### CODE REVIEW

**Review by mofhusseini — APPROVED** [review]
LGTM

**Comment by mofhusseini** [comment]
@WilliamXieCrypto FYI

**Comment by WilliamXieCrypto** [comment]
@mofhusseini Thanks, LGTM

**Review by WilliamXieCrypto — APPROVED** [review]

**Comment by mofhusseini** [comment]
Closing this PR as this change has been merged already

**Pull request closed without merging**
