### PR TITLE
Add upstream commits

### PR DESCRIPTION
**Pull request by mofhusseini**

### CODE REVIEW

**Review by crypto-facs — APPROVED** [review]

**Comment by crypto-facs** [comment]
🚀 🚀

**Comment by WilliamXieCrypto** [comment]
@mofhusseini @crypto-facs @calvinaco I tested this PR locally and found that some of the previous changes were lost, like some of css and svg color so maybe I can have a update for this PR, what do you guys think?

**Comment by WilliamXieCrypto** [comment]
@mofhusseini @crypto-facs @calvinaco Hey guys, I have updated some styles for this PR and conflicts resolved 🚀 🚀. Btw, this upstream merge bring some of styles that may not looking well(especially the dark mode), so we need get the feedback from design team after we close this PR.

**Review by WilliamXieCrypto — APPROVED** [review]

**Comment by mofhusseini** [comment]
> @mofhusseini @crypto-facs @calvinaco Hey guys, I have updated some styles for this PR and conflicts resolved 🚀 🚀. Btw, this upstream merge bring some of styles that may not looking well(especially the dark mode), so we need get the feedback from design team after we close this PR.

Awesome! Thank you for taking the time to do this William :). Much appreciated

**Pull request merged**
